### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by ljjTYJR** [StarRealMan/EINRUL#2]
In the import line of the file _eval.py_
https://github.com/StarRealMan/EINRUL/blob/a46fe396ccfd6a5700353a3f86d86bea15a76a68/eval.py?plain=1#L1

Where is the `evaluate .py` in the `utils` directory?

**Comment by StarRealMan** [comment]
Sorry, the file was not synchronized with the git repository due to previous mistakes, and it has been pushed now.

**Comment by ljjTYJR** [comment]
One thing I can not understand is that:
> "However, hash collision may occur in high-resolution layers, which may cause artifacts in undersupervised areas. To avoid this, we extract an additional feature vector from the input coordinate and concatenate them as our final feature."

How does this way can avoid hash collision since the hash collision is the properties of the limited-size hash table itself.

**Comment by StarRealMan** [comment]
You are right that the hash collision is the properties of the limited-size hash table itself.
The thing that we try to avoid is the artifact that introduced by hash collision.
In our experiments, additional feature directly from the input coordinate can alleviate this effect.

**Comment by ljjTYJR** [comment]
Another minor question:
For the `occNeRF` network:
https://github.com/StarRealMan/EINRUL/blob/7998cf76f4f657becbb96a31a101b0e50641d011/model/nerf.py?plain=1#L65-L90

When setting the network structure,
https://github.com/StarRealMan/EINRUL/blob/7998cf76f4f657becbb96a31a101b0e50641d011/model/nerf.py?plain=1#L80-L88
Since here the network only has two layers, why a skip operation is needed?

**Comment by StarRealMan** [comment]
You are right, because the network is shallow, skip operation may be dispensable.
We have not tested the performance without skip operation, but it may have no effect on the results.
