### ISSUE TITLE
Questions about depth in code

### ISSUE THREAD

**Issue by Frank-JP621** [StarRealMan/EINRUL#4]
Hi, your work looks pretty cool.

However, I have some questions about the depth of your code. Why did you choose to directly take the z value as the depth instead of using the norm to get the depth of points?

https://github.com/StarRealMan/EINRUL/blob/bbd02da14a5763a6e5ea47d22ee2316b71b994fa/utils/render.py#L49

**Comment by StarRealMan** [comment]
Thank you for following our work.
Actually, the using of z value or the norm as depth supervision work the same way if you use corresponding way for depth rendering.
In our work, we use z value for depth rendering, so we also need to use z value for depth supervision.
The rendering code can be found here:
https://github.com/StarRealMan/EINRUL/blob/bbd02da14a5763a6e5ea47d22ee2316b71b994fa/utils/render.py#L25C5-L25C12
https://github.com/StarRealMan/EINRUL/blob/bbd02da14a5763a6e5ea47d22ee2316b71b994fa/utils/render.py#L99C4-L99C49
It depends on how `rays_d` is normalized.

Hope this answer can solve your problem.

**Comment by AbdelFarhan** [comment]
Hi, I have a follow up question, what if I want to use a 360 degree FOV lidar? in this case using z directly is not valid.
